### PR TITLE
Add click function to options

### PR DESCRIPTION
**Pull request by hellodavecooper**
This PR implements onClick option. This gives the ability to write a custom function that makes other changes to the chart when a legend is clicked (other than just hiding that legend's series). Provides access to the whole chart, and the click event.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Thanks for the PR!
I think `chartFnc` is a weird name, maybe `onClick` is better? That would make it more clear what it does.
Also, why do you re-assign to `chart`? You could just modify the `chart` instance in your function.
Could you make a test for this?

**Comment by hellodavecooper** [comment]
Good ideas @SpaceK33z. I've made those changes, and will add a test next.

**Comment by SpaceK33z** [comment]
Thank you, sorry for the delay!

**Comment by SpaceK33z** [comment]
Released with version `0.3.0`

**Pull request merged**
