### PR TITLE
Refactoring and simplification

### PR DESCRIPTION
**Pull request by amichair**
These commits clean up, refactor and simplify the code, so that it is easier to read, maintain, contribute and extend. Functionality should remain exactly the same.

### CODE REVIEW

**Comment by tarekis** [comment]
@SpaceK33z Do you know anything about this PR? It's conflicting and by description adds no logic, not sure if we need this, as with the major update to support React.js usage (https://github.com/CodeYellowBV/chartist-plugin-legend/issues/5) refactoring will be done anyways.

**Comment by amichair** [comment]
Unfortunately, this PR was ignored for months and the code in master diverged too much for the conflicts to be reconciled, so all that work went to waste. Ironically, the purpose of this PR is to make the code more maintainable and well organized so that conflicts like these would be less likely to occur than with a big bowl of spaghetti code...

In any case, I threw away the previous PR commits and redid it from scratch in the same spirit. Please try to review it within a reasonable timeframe this time, if possible, so that it can be merged and/or improved before it becomes too stale again. It will certainly make additional contributions down the road much easier for all of us.

**Comment by tarekis** [comment]
Hmmm, I guess @SpaceK33z is out completely, and I rarely have time to check GitHub after work, I'll cancel some stuff today and look at it, I'll just review this on my own then.
Sorry for the inconvenience @amichair, I wanted @SpaceK33z to confirm this and didn't look into it anymore...

**Review by tarekis — APPROVED** [review]

**Comment by tarekis** [comment]
LGTM

**Comment by amichair** [comment]
Thanks for doing this really quick :-)

**Pull request merged**
