### PR TITLE
add demo for #28

### PR DESCRIPTION
**Pull request by tarekis**
Minified existing and added another example for the demo page. Creating examples is now a lot easier and you the code that is displayed is now generated from the actual code used to create the chart, had a minor inconsistence for this case; it's now fixed and simplified.

### CODE REVIEW

**Comment by tarekis** [comment]
docs-PR for #30 and minor improvement to the site.

**Comment by SpaceK33z** [comment]
Thanks, nice work again!

**Comment by tarekis** [comment]
Oh well, the demo page throws since it still has the `0.5` `chartist-plugin-legend` source-code. The updated code as of PR #30 should be in gh-pages too for `gh-pages` to include the updates sources.. sorry about that, i didn't think of that. You'll have to merge the new `chartist-plugin-legend.js` from `master` into `gh-pages` for it to work. Might be a good idea to unmirror `gh-pages` from `master` and just throw in a minified compiled version of the source.

**Comment by SpaceK33z** [comment]
I published `0.6.0` now and `gh-pages` is up-to-date. Thanks again.

Hm, we wouldn't even have that problem if we would only use the `master` branch with a `docs/` folder. It would also make it easier to add documentation for a new feature in 1 PR, so I'll probably switch to that sometime.

**Comment by tarekis** [comment]
That'd eliminate that problem, yeah, seems like a pretty neat idea!

**Pull request merged**
