### PR TITLE
meteor integration

### PR DESCRIPTION
**Pull request by mattiLeBlanc**
Hi

I'm a Meteor.js dev and volunteer package maintainer for Meteor. I using Chartist and I wanted to add your legend plugin. However there is no package in Meteor yet.

This PR will let you directly publish updated versions of the library as they become available. All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer.

I've already published the current version of the package on Atmosphere (Meteor's package directory). When you release new versions, you can publish them to Atmosphere with grunt meteor.

Thanks & best regards,
Mattijs

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Hi @mattiLeBlanc, thanks for your PR. However, wouldn't it be better to maintain a fork for this? I have never used meteor, and personally I find it nonsense to have so much boilerplate for such a simple plugin. Is this really necessary?

**Comment by mattiLeBlanc** [comment]
I am happy to keep it as a fork, unless it is going to change a lot (the source).
At Meteor they suggest to ask the plugin owner to merge it so that the package can automatically be published.
However, I am running in some issues with multiple charts + legends and state changes. So I might have to fix this in the fork which will make it different anyway.

**Comment by mattiLeBlanc** [comment]
I have amended your plugin a little bit because it was duplicating the legend in Meteor when using reactive Autorun.
Have a look at my fork, branch meteor-integration.

Concerning your merge concerns: If you would merge, it would only add a meteor folder which defines the meteor package so that people can load it as a meteor package. Having one source would benefit reusability.
I could also create a new package based on the fork but then any enhancement would be done in this fork and not in your original source.
Your call.

**Comment by SpaceK33z** [comment]
Meteor should be able to [load npm packages now](https://guide.meteor.com/using-npm-packages.html), so this package should work automatically.

**Pull request closed without merging**
